get:
    tags:
        - games
    responses:
        '200':
            content:
                application/json:
                    schema:
                        type: array
                        items:
                            type: string
                    examples:
                        Example:
                            value: '{id: 1, name: "Witcher 3", price: 29.99}'
            description: Returns full details of a given id game
    summary: Get a list of all games
    description: Returns a list of all games in API
